<?php
declare(strict_types=1);
require dirname(__DIR__).'/src/Core.php';
use Portal\Core as C;
function field(string $name,int $max=255): string {return trim(mb_substr((string)($_POST[$name]??''),0,$max));}
function fail(string $message,int $code=400): never {http_response_code($code);page('Errore','<div class="card"><h1>Operazione non riuscita</h1><p>'.C::h($message).'</p><p><a href="/">Torna all’area clienti</a></p></div>');exit;}
function page(string $title,string $content,?array $user=null): void {$name=$user?C::h($user['first_name'].' '.$user['last_name']):'';$nav=$user?'<div class="user">'.$name.' · '.($user['role']==='admin'?'Amministrazione':'Cliente').' <form method="post" action="/?action=logout"><input type="hidden" name="_csrf" value="'.C::csrf().'"><button class="link">Esci</button></form></div>':'';echo '<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta http-equiv="Cache-Control" content="no-store"><title>'.C::h($title).' · CA Automazione</title><link rel="stylesheet" href="/style.css"></head><body><header><div class="shell top"><a class="brand" href="/">C.A. Automazione <span>Area Clienti</span></a>'.$nav.'</div></header><main class="shell">'.$content.'</main></body></html>';}
function inputCsrf(): string {return '<input type="hidden" name="_csrf" value="'.C::csrf().'">';}
function cleanFilename(string $name): string {$name=basename(str_replace('\\','/',$name));return mb_substr(preg_replace('/[\x00-\x1f\x7f]/u','',$name) ?: 'documento',0,180);}
function document(int $id,array $u): array|false {return C::row('SELECT d.* FROM documents d JOIN users r ON r.id=d.recipient_id AND r.active=1 JOIN companies c ON c.id=d.company_id AND c.active=1 JOIN plants p ON p.id=d.plant_id AND p.active=1 WHERE d.id=? AND d.deleted_at IS NULL AND d.revoked_at IS NULL AND ( ? = ? OR (d.recipient_id=? AND d.company_id=? AND EXISTS(SELECT 1 FROM user_plants up WHERE up.user_id=? AND up.plant_id=d.plant_id)))',[$id,$u['role'],'admin',$u['id'],$u['company_id'],$u['id']]);}
try {
 C::session();$action=(string)($_GET['action']??'');
 if($_SERVER['REQUEST_METHOD']==='POST'){
 C::checkCsrf();
 if($action==='login'){$email=mb_strtolower(field('email',254));$ip=inet_pton($_SERVER['REMOTE_ADDR']??'')?:null;$count=C::row('SELECT COUNT(*) n FROM login_attempts WHERE email=? AND occurred_at>UTC_TIMESTAMP()-INTERVAL 15 MINUTE',[$email]);if((int)$count['n']>=8)fail('Troppi tentativi. Riprova tra 15 minuti.',429);C::exec('INSERT INTO login_attempts(email,ip) VALUES(?,?)',[$email,$ip]);$u=C::row('SELECT * FROM users WHERE email=? AND active=1',[$email]);if(!$u||!password_verify((string)($_POST['password']??''),$u['password_hash']))fail('Credenziali non valide.',401);C::exec('DELETE FROM login_attempts WHERE email=?',[$email]);session_regenerate_id(true);$_SESSION['uid']=$u['id'];$_SESSION['session_version']=(int)$u['session_version'];$_SESSION['csrf']=bin2hex(random_bytes(32));C::go('/');}
 if($action==='logout'){C::logout();C::go('/');}
 if($action==='request_reset'){$email=mb_strtolower(field('email',254));if(filter_var($email,FILTER_VALIDATE_EMAIL)){$target=C::row('SELECT id,first_name,last_name,email FROM users WHERE email=? AND active=1',[$email]);if($target){$count=C::row('SELECT COUNT(*) n FROM password_reset_tokens WHERE user_id=? AND created_at>UTC_TIMESTAMP()-INTERVAL 1 HOUR',[$target['id']]);if((int)$count['n']<3){$token=bin2hex(random_bytes(32));C::exec('INSERT INTO password_reset_tokens(user_id,token_hash,expires_at) VALUES(?,?,DATE_ADD(UTC_TIMESTAMP(),INTERVAL 30 MINUTE))',[$target['id'],hash('sha256',$token)]);$id=(int)C::db()->lastInsertId();C::queue('password_reset',$email,'Reimposta la password · CA Automazione','Per impostare una nuova password, apri entro 30 minuti: '.C::config()['base_url'].'/?action=reset&token='.$token.' Se non hai richiesto questa operazione, ignora il messaggio.','reset:'.$id);}}}C::go('/?reset_sent=1');}
 if($action==='set_password'){$token=(string)($_POST['token']??'');$new=(string)($_POST['new']??'');if(!preg_match('/^[a-f0-9]{64}$/D',$token)||strlen($new)<12||strlen($new)>200)fail('Collegamento o password non validi.');C::db()->beginTransaction();try{$reset=C::row('SELECT id,user_id FROM password_reset_tokens WHERE token_hash=? AND used_at IS NULL AND expires_at>UTC_TIMESTAMP() FOR UPDATE',[hash('sha256',$token)]);if(!$reset){C::db()->rollBack();fail('Il collegamento è scaduto o già utilizzato.');}C::exec('UPDATE users SET password_hash=?,session_version=session_version+1 WHERE id=?',[password_hash($new,PASSWORD_DEFAULT),$reset['user_id']]);C::exec('UPDATE password_reset_tokens SET used_at=UTC_TIMESTAMP() WHERE user_id=? AND used_at IS NULL',[$reset['user_id']]);C::db()->commit();}catch(Throwable $e){if(C::db()->inTransaction())C::db()->rollBack();throw $e;}C::logout();C::go('/?password_updated=1');}

 $u=C::requireUser();
 if($action==='password'){$old=(string)($_POST['old']??'');$new=(string)($_POST['new']??'');$hash=C::row('SELECT password_hash FROM users WHERE id=?',[$u['id']]);if(!password_verify($old,$hash['password_hash'])||strlen($new)<12||strlen($new)>200)fail('La password attuale è errata oppure la nuova password non ha almeno 12 caratteri.');C::exec('UPDATE users SET password_hash=?,session_version=session_version+1 WHERE id=?',[password_hash($new,PASSWORD_DEFAULT),$u['id']]);$_SESSION['session_version']++;session_regenerate_id(true);C::audit((int)$u['id'],'password_changed');C::go('/?saved=1');}
 if($u['role']!=='admin')fail('Operazione non consentita.',403);
 if($action==='company'){$n=field('name',180);if($n==='')fail('Inserisci il nome dell’azienda.');C::exec('INSERT INTO companies(name) VALUES(?)',[$n]);C::audit((int)$u['id'],'company_created',(int)C::db()->lastInsertId());C::go('/?tab=accounts&saved=1');}
 if($action==='plant'){$company=(int)($_POST['company_id']??0);$n=field('name',180);if(!$company||$n===''||!C::row('SELECT id FROM companies WHERE id=? AND active=1',[$company]))fail('Azienda o nome impianto non valido.');C::exec('INSERT INTO plants(company_id,name) VALUES(?,?)',[$company,$n]);C::audit((int)$u['id'],'plant_created',(int)C::db()->lastInsertId());C::go('/?tab=accounts&saved=1');}
 if($action==='account'){$company=(int)($_POST['company_id']??0);$plant=(int)($_POST['plant_id']??0);$first=field('first_name',100);$last=field('last_name',100);$email=mb_strtolower(field('email',254));$password=(string)($_POST['password']??'');if(!$first||!$last||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($password)<12||!C::row('SELECT id FROM plants WHERE id=? AND company_id=? AND active=1',[$plant,$company]))fail('Controlla i dati: password di almeno 12 caratteri e impianto appartenente all’azienda.');C::db()->beginTransaction();try{C::exec("INSERT INTO users(company_id,first_name,last_name,email,password_hash,role) VALUES(?,?,?,?,?,'client')",[$company,$first,$last,$email,password_hash($password,PASSWORD_DEFAULT)]);$id=(int)C::db()->lastInsertId();C::exec('INSERT INTO user_plants(user_id,plant_id) VALUES(?,?)',[$id,$plant]);C::audit((int)$u['id'],'user_created',$id);C::db()->commit();}catch(Throwable $e){C::db()->rollBack();throw $e;}C::go('/?tab=accounts&saved=1');}
 if($action==='edit_user'){$id=(int)($_POST['id']??0);$first=field('first_name',100);$last=field('last_name',100);$email=mb_strtolower(field('email',254));$target=C::row("SELECT id FROM users WHERE id=? AND role='client'",[$id]);if(!$target||$first===''||$last===''||!filter_var($email,FILTER_VALIDATE_EMAIL))fail('Dati account non validi.');C::exec('UPDATE users SET first_name=?,last_name=?,email=? WHERE id=?',[$first,$last,$email,$id]);C::audit((int)$u['id'],'user_updated',$id);C::go('/?tab=accounts&saved=1');}
 if($action==='grant_plant'||$action==='revoke_plant'){$id=(int)($_POST['id']??0);$plant=(int)($_POST['plant_id']??0);$target=C::row("SELECT id,company_id FROM users WHERE id=? AND role='client'",[$id]);if(!$target||!C::row('SELECT id FROM plants WHERE id=? AND company_id=? AND active=1',[$plant,$target['company_id']]))fail('Impianto non valido per questa persona.',403);if($action==='grant_plant')C::exec('INSERT IGNORE INTO user_plants(user_id,plant_id) VALUES(?,?)',[$id,$plant]);else C::exec('DELETE FROM user_plants WHERE user_id=? AND plant_id=?',[$id,$plant]);C::audit((int)$u['id'],$action,$id);C::go('/?tab=accounts&saved=1');}
 if($action==='reset_user_password'){$id=(int)($_POST['id']??0);$new=(string)($_POST['new_password']??'');if(strlen($new)<12||strlen($new)>200||!C::row("SELECT id FROM users WHERE id=? AND role='client'",[$id]))fail('Account o password non validi.');C::exec('UPDATE users SET password_hash=?,session_version=session_version+1 WHERE id=?',[password_hash($new,PASSWORD_DEFAULT),$id]);C::audit((int)$u['id'],'password_reset_by_admin',$id);C::go('/?tab=accounts&saved=1');}
 if($action==='toggle_user'){$id=(int)($_POST['id']??0);$target=C::row("SELECT id,role,active FROM users WHERE id=? AND role='client'",[$id]);if(!$target)fail('Account non valido.');C::exec('UPDATE users SET active=?,session_version=session_version+1 WHERE id=?',[$target['active']?0:1,$id]);C::audit((int)$u['id'],$target['active']?'user_disabled':'user_enabled',$id);C::go('/?tab=accounts&saved=1');}
 if($action==='upload'){$recipient=(int)($_POST['recipient_id']??0);$plant=(int)($_POST['plant_id']??0);$title=field('title',220);$r=C::row("SELECT u.id,u.company_id,u.email,u.first_name,u.last_name,p.name plant FROM users u JOIN user_plants up ON up.user_id=u.id JOIN plants p ON p.id=up.plant_id AND p.company_id=u.company_id AND p.active=1 JOIN companies c ON c.id=u.company_id AND c.active=1 WHERE u.id=? AND p.id=? AND u.active=1 AND u.role='client'",[$recipient,$plant]);$f=$_FILES['file']??null;$cfg=C::config();if(!$r||$title===''||!$f||$f['error']!==UPLOAD_ERR_OK||!is_uploaded_file($f['tmp_name'])||$f['size']<1||$f['size']>$cfg['max_upload_bytes'])fail('Controlla destinatario, impianto e dimensione del file.');$mime=(new finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name']);$allowed=['application/pdf','image/png','image/jpeg','text/plain','application/zip','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'];if(!in_array($mime,$allowed,true))fail('Tipo di file non consentito.');$dir=$cfg['storage_path'];if(!is_dir($dir)||!is_writable($dir)||realpath($dir)===false||str_starts_with(realpath($dir),realpath(__DIR__)))fail('Archivio privato non configurato correttamente.',503);$capacity=$cfg['capacity_bytes'];if($capacity!==null){$used=(int)C::row('SELECT COALESCE(SUM(bytes),0) n FROM documents WHERE deleted_at IS NULL')['n'];if($used+$f['size']>$capacity)fail('Spazio insufficiente per questo documento.',507);} $key=bin2hex(random_bytes(32));$dest=rtrim($dir,'/').'/'.$key;if(!move_uploaded_file($f['tmp_name'],$dest))fail('Caricamento non riuscito.',503);chmod($dest,0600);try{C::db()->beginTransaction();C::exec('INSERT INTO documents(company_id,plant_id,recipient_id,title,original_name,storage_key,mime,bytes,sha256,created_by) VALUES(?,?,?,?,?,?,?,?,?,?)',[$r['company_id'],$plant,$recipient,$title,cleanFilename($f['name']),$key,$mime,$f['size'],hash_file('sha256',$dest),$u['id']]);$id=(int)C::db()->lastInsertId();C::queue('new_document',$r['email'],'Nuovo documento disponibile · CA Automazione','Buongiorno '.$r['first_name'].' '.$r['last_name'].', un documento ('.$title.') è disponibile nella tua Area Clienti: '.$cfg['base_url'],'new:'.$id);C::audit((int)$u['id'],'document_uploaded',$id);C::db()->commit();}catch(Throwable $e){C::db()->rollBack();unlink($dest);throw $e;}C::go('/?saved=1');}
 if($action==='edit_document'){$id=(int)($_POST['id']??0);$title=field('title',220);if($title===''||!C::row('SELECT id FROM documents WHERE id=? AND deleted_at IS NULL',[$id]))fail('Documento non valido.');C::exec('UPDATE documents SET title=? WHERE id=?',[$title,$id]);C::audit((int)$u['id'],'document_updated',$id);C::go('/?saved=1');}
 if($action==='bulk_delete'){$ids=array_values(array_unique(array_filter(array_map('intval',(array)($_POST['ids']??[])),fn($n)=>$n>0)));if(!$ids||count($ids)>100)fail('Seleziona da 1 a 100 documenti.');$files=[];foreach($ids as $id){$d=C::row('SELECT id,storage_key FROM documents WHERE id=? AND deleted_at IS NULL',[$id]);if(!$d)fail('Uno dei documenti non è più disponibile.');$files[]=$d;}foreach($files as $f){$path=rtrim(C::config()['storage_path'],'/').'/'.$f['storage_key'];if(is_file($path)&&!is_writable($path))fail('Un file non può essere eliminato.');}C::db()->beginTransaction();try{foreach($files as $f){C::exec('UPDATE documents SET deleted_at=UTC_TIMESTAMP(),revoked_at=COALESCE(revoked_at,UTC_TIMESTAMP()) WHERE id=?',[$f['id']]);C::audit((int)$u['id'],'document_deleted',(int)$f['id']);}C::db()->commit();}catch(Throwable $e){C::db()->rollBack();throw $e;}foreach($files as $f){$path=rtrim(C::config()['storage_path'],'/').'/'.$f['storage_key'];if(is_file($path)&&!unlink($path))error_log('Cleanup file failed: '.$f['id']);}C::go('/?tab=archive&saved=1');}
 if($action==='revoke'){$id=(int)($_POST['id']??0);if(!C::row('SELECT id FROM documents WHERE id=? AND deleted_at IS NULL',[$id]))fail('Documento non trovato.',404);C::exec('UPDATE documents SET revoked_at=UTC_TIMESTAMP() WHERE id=? AND revoked_at IS NULL',[$id]);C::audit((int)$u['id'],'document_revoked',$id);C::go('/?saved=1');}
 if($action==='delete'){$id=(int)($_POST['id']??0);$d=C::row('SELECT id,storage_key FROM documents WHERE id=? AND deleted_at IS NULL',[$id]);if(!$d)fail('Documento non trovato.',404);C::exec('UPDATE documents SET deleted_at=UTC_TIMESTAMP(),revoked_at=COALESCE(revoked_at,UTC_TIMESTAMP()) WHERE id=?',[$id]);C::audit((int)$u['id'],'document_deleted',$id);$path=rtrim(C::config()['storage_path'],'/').'/'.$d['storage_key'];if(is_file($path))unlink($path);C::go('/?tab=archive&saved=1');}
 fail('Operazione sconosciuta.',404);
 }
 if($action==='reset'){$token=(string)($_GET['token']??'');$reset=preg_match('/^[a-f0-9]{64}$/D',$token)?C::row('SELECT id FROM password_reset_tokens WHERE token_hash=? AND used_at IS NULL AND expires_at>UTC_TIMESTAMP()',[hash('sha256',$token)]):false;if(!$reset)fail('Il collegamento è scaduto o già utilizzato.');page('Nuova password','<section class="login card"><h1>Nuova password</h1><form method="post" action="/?action=set_password">'.inputCsrf().'<input type="hidden" name="token" value="'.C::h($token).'"><label>Password (almeno 12 caratteri)<input type="password" name="new" minlength="12" autocomplete="new-password" required></label><button class="primary">Salva nuova password</button></form></section>');exit;}
 $u=C::user();if(!$u&&in_array($action,['view','download'],true))fail('Accesso richiesto.',401);if(!$u){$message=isset($_GET['reset_sent'])?'<div class="notice">Se l’indirizzo è associato a un account, riceverai un collegamento per reimpostare la password.</div>':(isset($_GET['password_updated'])?'<div class="notice">Password aggiornata. Ora puoi accedere.</div>':'');page('Accedi',$message.'<section class="login card"><p class="eyebrow">Accesso riservato</p><h1>Area Clienti</h1><p>Accedi con le credenziali fornite da CA Automazione.</p><form method="post" action="/?action=login">'.inputCsrf().'<label>Email<input type="email" name="email" autocomplete="username" required></label><label>Password<input type="password" name="password" autocomplete="current-password" required></label><button class="primary">Accedi</button></form><details><summary>Password dimenticata?</summary><p>Ti invieremo un collegamento valido per 30 minuti.</p><form method="post" action="/?action=request_reset">'.inputCsrf().'<label>Email<input type="email" name="email" required></label><button class="subtle">Invia collegamento</button></form></details></section>');exit;}
 if($action==='view'||$action==='download'){$id=(int)($_GET['id']??0);$d=document($id,$u);if(!$d)fail('Documento non disponibile.',404);$path=rtrim(C::config()['storage_path'],'/').'/'.$d['storage_key'];if(!is_file($path))fail('File temporaneamente non disponibile.',503);$filename=cleanFilename($d['original_name']);header('Content-Type: '.$d['mime']);header('Content-Length: '.filesize($path));header('X-Content-Type-Options: nosniff');header('Cache-Control: no-store, private');header('Content-Security-Policy: sandbox');header('Content-Disposition: '.($action==='download'?'attachment':'inline').'; filename="documento"; filename*=UTF-8\'\''.rawurlencode($filename));if($action==='download'&&$u['role']==='client'){C::db()->beginTransaction();try{C::exec('INSERT INTO download_events(document_id,user_id,ip) VALUES(?,?,?)',[$id,$u['id'],inet_pton($_SERVER['REMOTE_ADDR']??'')?:null]);$event=(int)C::db()->lastInsertId();C::exec('UPDATE documents SET first_download_at=COALESCE(first_download_at,UTC_TIMESTAMP()) WHERE id=?',[$id]);C::queue('download',C::config()['admin_email'],'Documento scaricato · CA Automazione',$u['first_name'].' '.$u['last_name'].' ('.$u['email'].') ha avviato il download di '.$d['title'].' il '.C::date(gmdate('Y-m-d H:i:s')).' (ora italiana). Evento #'.$event,'download:'.$event);C::db()->commit();}catch(Throwable $e){C::db()->rollBack();throw $e;}}readfile($path);exit;}
 $saved=isset($_GET['saved'])?'<div class="notice">Modifica salvata.</div>':'';
 $tabs=['documents'=>'Documenti','accounts'=>'Clienti e impianti','events'=>'Download','archive'=>'Archivio file','settings'=>'Password'];$tab=(string)($_GET['tab']??'documents');if($u['role']==='client'){$tabs=['documents'=>'Da scaricare','archive'=>'Archivio','settings'=>'Password'];if(!isset($tabs[$tab]))$tab='documents';}
 $nav='<nav class="tabs">';foreach($tabs as $key=>$label)$nav.='<a class="'.($tab===$key?'active':'').'" href="/?tab='.$key.'">'.$label.'</a>';$nav.='</nav>';
 $body='<div class="heading"><div><p class="eyebrow">'.($u['role']==='admin'?'Amministrazione':'Documenti assegnati a te').'</p><h1>Area Clienti</h1></div></div>'.$saved.$nav;
 if($tab==='documents'&&$u['role']==='admin'){$people=C::all("SELECT u.id,u.first_name,u.last_name,u.email,u.company_id,p.id plant_id,p.name plant,c.name company FROM users u JOIN companies c ON c.id=u.company_id JOIN user_plants up ON up.user_id=u.id JOIN plants p ON p.id=up.plant_id WHERE u.role='client' AND u.active=1 AND c.active=1 AND p.active=1 ORDER BY c.name,u.last_name");$opts='';foreach($people as $p)$opts.='<option value="'.$p['id'].':'.$p['plant_id'].'">'.C::h($p['first_name'].' '.$p['last_name'].' · '.$p['company'].' / '.$p['plant'].' · '.$p['email']).'</option>';$body.='<section class="card"><h2>Carica un documento</h2><p>Seleziona una sola persona. Il suo nome e l’impianto sono mostrati insieme per evitare consegne errate.</p><form method="post" action="/?action=upload" enctype="multipart/form-data" id="upload">'.inputCsrf().'<div class="formgrid"><label>Titolo<input name="title" maxlength="220" required></label><label>Destinatario<select id="recipient" required><option value="">Seleziona una persona</option>'.$opts.'</select></label></div><input type="hidden" name="recipient_id" id="rid"><input type="hidden" name="plant_id" id="pid"><label>File<input type="file" name="file" required></label><button class="primary">Conferma e invia notifica</button></form><script>document.getElementById("upload").addEventListener("submit",e=>{let v=document.getElementById("recipient").value.split(":");if(v.length!==2){e.preventDefault();return}document.getElementById("rid").value=v[0];document.getElementById("pid").value=v[1];if(!confirm("Confermi la consegna a "+document.getElementById("recipient").selectedOptions[0].text+"?"))e.preventDefault()})</script></section>';$docs=C::all('SELECT d.*,u.first_name,u.last_name,u.email,c.name company,p.name plant FROM documents d JOIN users u ON u.id=d.recipient_id JOIN companies c ON c.id=d.company_id JOIN plants p ON p.id=d.plant_id WHERE d.deleted_at IS NULL ORDER BY d.created_at DESC LIMIT 200');}
 elseif($tab==='documents'||$tab==='archive'){$sql='SELECT d.*,p.name plant FROM documents d JOIN plants p ON p.id=d.plant_id JOIN companies c ON c.id=d.company_id WHERE d.recipient_id=? AND d.company_id=? AND d.deleted_at IS NULL AND d.revoked_at IS NULL AND c.active=1 AND p.active=1 AND EXISTS(SELECT 1 FROM user_plants up WHERE up.user_id=? AND up.plant_id=d.plant_id) AND d.first_download_at IS '.($tab==='archive'?'NOT NULL':'NULL').' ORDER BY d.created_at DESC';$docs=C::all($sql,[$u['id'],$u['company_id'],$u['id']]);}
 if(isset($docs)){$body.='<section class="card"><h2>'.($u['role']==='admin'?'Documenti consegnati':($tab==='archive'?'Archivio':'Da scaricare')).'</h2><div class="scroll"><table><thead><tr><th>Documento</th><th>'.($u['role']==='admin'?'Destinatario':'Impianto').'</th><th>Caricato</th><th>Stato / Azioni</th></tr></thead><tbody>';foreach($docs as $d){$body.='<tr><td><strong>'.C::h($d['title']).'</strong><small>'.C::h($d['original_name']).' · '.number_format($d['bytes']/1048576,1,',','.').' MB</small></td><td>'.($u['role']==='admin'?C::h($d['first_name'].' '.$d['last_name']).'<small>'.C::h($d['email'].' · '.$d['company'].' / '.$d['plant']).'</small>':C::h($d['plant'])).'</td><td>'.C::date($d['created_at']).'</td><td>';if($d['revoked_at'])$body.='<span class="pill">Revocato</span>';else{$body.='<a href="/?action=view&id='.$d['id'].'" target="_blank" rel="noopener">Visualizza</a> · <a href="/?action=download&id='.$d['id'].'">Scarica</a>';}if($u['role']==='admin')$body.='<details><summary>Modifica titolo</summary><form method="post" action="/?action=edit_document">'.inputCsrf().'<input type="hidden" name="id" value="'.$d['id'].'"><input name="title" value="'.C::h($d['title']).'" required maxlength="220"><button class="subtle">Salva</button></form></details><small>'.($d['first_download_at']?'Primo download: '.C::date($d['first_download_at']):'Da scaricare').'</small><form method="post" action="/?action=revoke" onsubmit="return confirm(\'Revocare l’accesso al documento?\')">'.inputCsrf().'<input type="hidden" name="id" value="'.$d['id'].'"><button class="subtle">Revoca accesso</button></form>'; $body.='</td></tr>';}if(!$docs)$body.='<tr><td colspan="4">Nessun documento in questa sezione.</td></tr>';$body.='</tbody></table></div></section>';}
 if($tab==='accounts'&&$u['role']==='admin'){$companies=C::all('SELECT * FROM companies ORDER BY name');$plants=C::all('SELECT p.*,c.name company FROM plants p JOIN companies c ON c.id=p.company_id ORDER BY c.name,p.name');$users=C::all("SELECT u.*,c.name company FROM users u JOIN companies c ON c.id=u.company_id WHERE u.role='client' ORDER BY c.name,u.last_name");$co='';foreach($companies as $c)$co.='<option value="'.$c['id'].'">'.C::h($c['name']).'</option>';$po='';foreach($plants as $p)$po.='<option value="'.$p['id'].'" data-company="'.$p['company_id'].'">'.C::h($p['company'].' / '.$p['name']).'</option>';$body.='<div class="cols"><section class="card"><h2>Nuova azienda</h2><form method="post" action="/?action=company">'.inputCsrf().'<label>Nome<input name="name" required></label><button class="primary">Aggiungi azienda</button></form></section><section class="card"><h2>Nuovo impianto</h2><form method="post" action="/?action=plant">'.inputCsrf().'<label>Azienda<select name="company_id" required>'.$co.'</select></label><label>Nome impianto<input name="name" required></label><button class="primary">Aggiungi impianto</button></form></section></div><section class="card"><h2>Nuovo account cliente</h2><p>Consegna la password iniziale alla persona attraverso un canale sicuro. Il cliente potrà cambiarla dopo l’accesso.</p><form method="post" action="/?action=account">'.inputCsrf().'<div class="formgrid"><label>Nome<input name="first_name" required></label><label>Cognome<input name="last_name" required></label><label>Email<input name="email" type="email" required></label><label>Password iniziale<input name="password" type="password" minlength="12" required></label><label>Azienda<select name="company_id" id="company" required><option value="">Seleziona</option>'.$co.'</select></label><label>Impianto<select name="plant_id" id="plant" required><option value="">Seleziona</option>'.$po.'</select></label></div><button class="primary">Crea account</button></form><script>const company=document.getElementById("company"),plant=document.getElementById("plant");company.onchange=()=>{plant.value="";[...plant.options].forEach(o=>{if(o.value)o.hidden=o.dataset.company!==company.value})};company.onchange()</script></section><section class="card"><h2>Account</h2><div class="scroll"><table><thead><tr><th>Persona</th><th>Azienda</th><th>Stato</th><th>Azione</th></tr></thead><tbody>';foreach($users as $x)$body.='<tr><td>'.C::h($x['first_name'].' '.$x['last_name']).'<small>'.C::h($x['email']).'</small></td><td>'.C::h($x['company']).'</td><td>'.($x['active']?'Attivo':'Disattivato').'</td><td><form method="post" action="/?action=toggle_user">'.inputCsrf().'<input type="hidden" name="id" value="'.$x['id'].'"><button class="subtle">'.($x['active']?'Disattiva':'Riattiva').'</button></form></td></tr>';$body.='</tbody></table></div></section>';}
 if($tab==='accounts'&&$u['role']==='admin'){
  $grants=C::all('SELECT user_id,plant_id FROM user_plants');$allowed=[];foreach($grants as $g)$allowed[(int)$g['user_id']][(int)$g['plant_id']]=true;
  $body.='<section class="card"><h2>Modifica account e permessi</h2><p>Apri una persona per aggiornare i dati e gli impianti consentiti.</p>';
  foreach($users as $person){
   $id=(int)$person['id'];$body.='<details class="account"><summary><strong>'.C::h($person['first_name'].' '.$person['last_name']).'</strong> · '.C::h($person['company']).'<small>'.C::h($person['email']).'</small></summary>';
   $body.='<form method="post" action="/?action=edit_user">'.inputCsrf().'<input type="hidden" name="id" value="'.$id.'"><div class="formgrid"><label>Nome<input name="first_name" value="'.C::h($person['first_name']).'" required></label><label>Cognome<input name="last_name" value="'.C::h($person['last_name']).'" required></label><label>Email<input name="email" type="email" value="'.C::h($person['email']).'" required></label></div><button class="subtle">Salva account</button></form>';
   $body.='<h3>Impianti consentiti</h3><div class="plant-list">';foreach($plants as $plant)if((int)$plant['company_id']===(int)$person['company_id']){$has=isset($allowed[$id][(int)$plant['id']]);$body.='<form method="post" action="/?action='.($has?'revoke_plant':'grant_plant').'">'.inputCsrf().'<input type="hidden" name="id" value="'.$id.'"><input type="hidden" name="plant_id" value="'.$plant['id'].'"><span>'.C::h($plant['name']).'</span><button class="subtle">'.($has?'Rimuovi accesso':'Concedi accesso').'</button></form>';}$body.='</div>';
   $body.='<form method="post" action="/?action=reset_user_password">'.inputCsrf().'<input type="hidden" name="id" value="'.$id.'"><label>Nuova password iniziale<input type="password" name="new_password" minlength="12" required></label><button class="subtle">Reimposta password</button></form></details>';
  }$body.='</section>';
 }
 if($tab==='events'&&$u['role']==='admin'){$events=C::all('SELECT e.*,d.title,u.first_name,u.last_name,u.email,c.name company,p.name plant FROM download_events e JOIN documents d ON d.id=e.document_id JOIN users u ON u.id=e.user_id JOIN companies c ON c.id=d.company_id JOIN plants p ON p.id=d.plant_id ORDER BY e.started_at DESC LIMIT 300');$body.='<section class="card"><h2>Download registrati</h2><p>La data indica l’avvio della trasmissione dal server, non la conferma del salvataggio sul dispositivo.</p><div class="scroll"><table><thead><tr><th>Documento</th><th>Persona</th><th>Azienda / impianto</th><th>Data e ora (Italia)</th></tr></thead><tbody>';foreach($events as $e)$body.='<tr><td>'.C::h($e['title']).'</td><td>'.C::h($e['first_name'].' '.$e['last_name']).'<small>'.C::h($e['email']).'</small></td><td>'.C::h($e['company'].' / '.$e['plant']).'</td><td>'.C::date($e['started_at']).'</td></tr>';$body.='</tbody></table></div></section>';}
 if($tab==='archive'&&$u['role']==='admin'){
  $files=C::all('SELECT d.id,d.title,d.bytes,d.created_at,d.deleted_at,u.first_name,u.last_name,c.name company FROM documents d JOIN users u ON u.id=d.recipient_id JOIN companies c ON c.id=d.company_id ORDER BY d.created_at DESC LIMIT 500');
  $used=(int)C::row('SELECT COALESCE(SUM(bytes),0) n FROM documents WHERE deleted_at IS NULL')['n'];
  $body.='<section class="card"><h2>Archivio file</h2><p>File attivi: '.number_format($used/1073741824,2,',','.').' GiB. La soglia email è 2 GiB residui, quando la quota è configurata.</p><form method="post" action="/?action=bulk_delete" onsubmit="return confirm(\'Eliminare i documenti selezionati? I clienti perderanno accesso e i file verranno rimossi.\')">'.inputCsrf().'<div class="scroll"><table><thead><tr><th>Seleziona</th><th>Documento</th><th>Destinatario</th><th>Data</th><th>Dimensione</th></tr></thead><tbody>';
  foreach($files as $f)$body.='<tr><td>'.($f['deleted_at']?'—':'<input type="checkbox" name="ids[]" value="'.$f['id'].'" aria-label="Seleziona '.C::h($f['title']).'">').'</td><td>'.C::h($f['title']).($f['deleted_at']?' <small>Eliminato</small>':'').'</td><td>'.C::h($f['first_name'].' '.$f['last_name'].' · '.$f['company']).'</td><td>'.C::date($f['created_at']).'</td><td>'.number_format($f['bytes']/1048576,1,',','.').' MB</td></tr>';
  if(!$files)$body.='<tr><td colspan="5">Nessun file.</td></tr>';
  $body.='</tbody></table></div><button class="danger">Elimina selezionati</button></form></section>';
 }
 if($tab==='settings')$body.='<section class="card narrow"><h2>Cambia password</h2><form method="post" action="/?action=password">'.inputCsrf().'<label>Password attuale<input type="password" name="old" required></label><label>Nuova password (almeno 12 caratteri)<input type="password" name="new" minlength="12" required></label><button class="primary">Aggiorna password</button></form></section>';
 page('Area Clienti',$body,$u);
} catch(Throwable $e){error_log('Portal error: '.$e->getMessage());http_response_code(503);page('Servizio non disponibile','<section class="card"><h1>Servizio temporaneamente non disponibile</h1><p>Riprova più tardi o contatta CA Automazione.</p></section>');}
