<?php
declare(strict_types=1);
require dirname(__DIR__).'/src/Core.php';
use Portal\Core as C;
function field(string $name,int $max=255): string {return trim(mb_substr((string)($_POST[$name]??''),0,$max));}
function fail(string $message,int $code=400): never {http_response_code($code);page('Errore','<div class="card"><h1>Operazione non riuscita</h1><p>'.C::h($message).'</p><p><a href="/">Torna all’area clienti</a></p></div>');exit;}
function page(string $title,string $content,?array $user=null): void {$siteUrl=C::h((string)(C::config()['site_url']??'https://caniatoautomazione.com/'));$name=$user?C::h($user['first_name'].' '.$user['last_name']):'';$nav=$user?'<div class="user">'.$name.' · '.($user['role']==='admin'?'Amministrazione':($user['role']==='operator'?'Operatore CA Automazione':'Cliente')).' <form method="post" action="/?action=logout"><input type="hidden" name="_csrf" value="'.C::csrf().'"><button class="link">Esci</button></form></div>':'';if($user&&isset($_SESSION['impersonator_uid']))$content='<div class="impersonation"><strong>Vista del cliente '.C::h($user['first_name'].' '.$user['last_name']).'</strong><span>Accesso amministrativo registrato. I download del cliente sono disattivati in questa vista.</span><form method="post" action="/?action=stop_impersonation">'.inputCsrf().'<button class="subtle">Torna all’amministrazione</button></form></div>'.$content;echo '<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta http-equiv="Cache-Control" content="no-store"><title>'.C::h($title).' · C.A. Automazione &amp; Strumentazione</title><link rel="icon" href="/assets/logo-quadrato.svg" type="image/svg+xml"><link rel="stylesheet" href="/style.css"><script src="/portal.js" defer></script></head><body><header><div class="shell top"><a class="brand" href="/" aria-label="C.A. Automazione &amp; Strumentazione · Area Clienti"><img src="/assets/logo-quadrato.svg" alt=""><span>C.A. Automazione &amp; Strumentazione<small>Area Clienti</small></span></a><div class="top-actions"><a class="back-site" href="'.$siteUrl.'">Torna al sito internet</a>'.$nav.'</div></div></header><main class="shell">'.$content.'</main></body></html>';}
function inputCsrf(): string {return '<input type="hidden" name="_csrf" value="'.C::csrf().'">';}
function cleanFilename(string $name): string {$name=basename(str_replace('\\','/',$name));return mb_substr(preg_replace('/[\x00-\x1f\x7f]/u','',$name) ?: 'documento',0,180);}
function document(int $id,array $u): array|false {$doc=C::row('SELECT d.* FROM documents d JOIN users r ON r.id=d.recipient_id AND r.active=1 AND r.deleted_at IS NULL JOIN companies c ON c.id=d.company_id AND c.active=1 JOIN plants p ON p.id=d.plant_id AND p.active=1 WHERE d.id=? AND d.deleted_at IS NULL AND d.revoked_at IS NULL AND ( ? IN (\'admin\',\'operator\') OR (d.recipient_id=? AND d.company_id=? AND EXISTS(SELECT 1 FROM user_plants up WHERE up.user_id=? AND up.plant_id=d.plant_id)))',[$id,$u['role'],$u['id'],$u['company_id'],$u['id']]);return $doc&&($u['role']!=='client'||C::available($doc))?$doc:false;}
try {
 C::session();$action=(string)($_GET['action']??'');
 if($_SERVER['REQUEST_METHOD']==='POST'){
 C::checkCsrf();
 if($action==='login'){
  $email=mb_strtolower(field('email',254));$ip=inet_pton($_SERVER['REMOTE_ADDR']??'')?:null;
  $count=C::row('SELECT COUNT(*) n FROM login_attempts WHERE email=? AND occurred_at>UTC_TIMESTAMP()-INTERVAL 15 MINUTE',[$email]);
  if((int)$count['n']>=8)fail('Troppi tentativi. Riprova tra 15 minuti.',429);
  C::exec('INSERT INTO login_attempts(email,ip) VALUES(?,?)',[$email,$ip]);
  $u=C::row('SELECT * FROM users WHERE email=? AND active=1 AND deleted_at IS NULL',[$email]);
  if(!$u||!password_verify((string)($_POST['password']??''),$u['password_hash']))fail('Credenziali non valide.',401);if($u['role']==='admin'&&strcasecmp($u['email'],(string)C::config()['admin_email'])!==0)fail('L’account amministratore non è configurato correttamente.',503);
  $version=C::config()['privacy_version'];$recorded=$u['privacy_version']===$version && $u['privacy_accepted_at']!==null;
  if(!$recorded && empty($_POST['privacy_read']))fail('Leggi l’informativa privacy e conferma la presa visione prima di accedere.');
  if(!$recorded && !empty($_POST['remember_privacy']))C::exec('UPDATE users SET privacy_version=?,privacy_accepted_at=UTC_TIMESTAMP() WHERE id=?',[$version,$u['id']]);
  C::exec('DELETE FROM login_attempts WHERE email=?',[$email]);
  C::exec('INSERT INTO access_events(user_id,ip,user_agent) VALUES(?,?,?)',[$u['id'],$ip,mb_substr((string)($_SERVER['HTTP_USER_AGENT']??''),0,500)]);
  session_regenerate_id(true);$_SESSION['uid']=$u['id'];$_SESSION['session_version']=(int)$u['session_version'];$_SESSION['csrf']=bin2hex(random_bytes(32));C::go('/');
 }
 if($action==='logout'){C::logout();C::go('/');}
 if($action==='request_reset'){$email=mb_strtolower(field('email',254));if(filter_var($email,FILTER_VALIDATE_EMAIL)){$target=C::row('SELECT id,first_name,last_name,email FROM users WHERE email=? AND active=1 AND deleted_at IS NULL',[$email]);if($target){$count=C::row('SELECT COUNT(*) n FROM password_reset_tokens WHERE user_id=? AND created_at>UTC_TIMESTAMP()-INTERVAL 1 HOUR',[$target['id']]);if((int)$count['n']<3){$token=bin2hex(random_bytes(32));C::exec('INSERT INTO password_reset_tokens(user_id,token_hash,expires_at) VALUES(?,?,DATE_ADD(UTC_TIMESTAMP(),INTERVAL 30 MINUTE))',[$target['id'],hash('sha256',$token)]);$id=(int)C::db()->lastInsertId();C::queue('password_reset',$email,'Reimposta la password · C.A. Automazione & Strumentazione','Per impostare una nuova password, apri entro 30 minuti: '.C::config()['base_url'].'/?action=reset&token='.$token.' Se non hai richiesto questa operazione, ignora il messaggio.','reset:'.$id);}}}C::go('/?reset_sent=1');}
 if($action==='set_password'){$token=(string)($_POST['token']??'');$new=(string)($_POST['new']??'');if(!preg_match('/^[a-f0-9]{64}$/D',$token)||strlen($new)<12||strlen($new)>200)fail('Collegamento o password non validi.');C::db()->beginTransaction();try{$reset=C::row('SELECT t.id,t.user_id FROM password_reset_tokens t JOIN users u ON u.id=t.user_id AND u.active=1 AND u.deleted_at IS NULL WHERE t.token_hash=? AND t.used_at IS NULL AND t.expires_at>UTC_TIMESTAMP() FOR UPDATE',[hash('sha256',$token)]);if(!$reset){C::db()->rollBack();fail('Il collegamento è scaduto o già utilizzato.');}C::exec('UPDATE users SET password_hash=?,session_version=session_version+1 WHERE id=?',[password_hash($new,PASSWORD_DEFAULT),$reset['user_id']]);C::exec('UPDATE password_reset_tokens SET used_at=UTC_TIMESTAMP() WHERE user_id=? AND used_at IS NULL',[$reset['user_id']]);C::db()->commit();}catch(Throwable $e){if(C::db()->inTransaction())C::db()->rollBack();throw $e;}C::logout();C::go('/?password_updated=1');}

 if($action==='stop_impersonation'){
  if(empty($_SESSION['impersonator_uid']))fail('Nessuna sessione cliente da chiudere.',403);
  $admin=C::row("SELECT id,session_version FROM users WHERE id=? AND role='admin' AND active=1 AND deleted_at IS NULL",[(int)$_SESSION['impersonator_uid']]);
  if(!$admin||(int)$admin['session_version']!==(int)($_SESSION['impersonator_version']??-1)){C::logout();C::go('/');}
  C::audit((int)$admin['id'],'impersonation_stopped',(int)($_SESSION['uid']??0));
  $_SESSION['uid']=$admin['id'];$_SESSION['session_version']=(int)$admin['session_version'];unset($_SESSION['impersonator_uid'],$_SESSION['impersonator_version']);session_regenerate_id(true);C::go('/?tab=accounts');
 }
 $u=C::requireUser();
 if($action==='password'){$old=(string)($_POST['old']??'');$new=(string)($_POST['new']??'');$hash=C::row('SELECT password_hash FROM users WHERE id=?',[$u['id']]);if(!password_verify($old,$hash['password_hash'])||strlen($new)<12||strlen($new)>200)fail('La password attuale è errata oppure la nuova password non ha almeno 12 caratteri.');C::exec('UPDATE users SET password_hash=?,session_version=session_version+1 WHERE id=?',[password_hash($new,PASSWORD_DEFAULT),$u['id']]);$_SESSION['session_version']++;session_regenerate_id(true);C::audit((int)$u['id'],'password_changed');C::go('/?saved=1');}
 if($u['role']==='client')fail('Operazione non consentita.',403);
 $fileActions=['upload','edit_document','bulk_delete'];
 if($u['role']==='operator'&&!in_array($action,$fileActions,true))fail('Operazione non consentita.',403);
 if($u['role']==='admin'&&!in_array($action,$fileActions,true)&&strcasecmp($u['email'],(string)C::config()['admin_email'])!==0)fail('Operazione non consentita.',403);
 if($action==='impersonate'){
  $id=(int)($_POST['id']??0);$target=C::row("SELECT id,session_version FROM users WHERE id=? AND role='client' AND active=1 AND deleted_at IS NULL",[$id]);
  if(!$target||isset($_SESSION['impersonator_uid']))fail('Account cliente non disponibile.',403);
  C::audit((int)$u['id'],'impersonation_started',$id);
  $_SESSION['impersonator_uid']=$u['id'];$_SESSION['impersonator_version']=(int)$u['session_version'];$_SESSION['uid']=$id;$_SESSION['session_version']=(int)$target['session_version'];session_regenerate_id(true);C::go('/');
 }
 if($action==='remove_user'){
  $id=(int)($_POST['id']??0);$target=C::row("SELECT id FROM users WHERE id=? AND role='client' AND deleted_at IS NULL",[$id]);
  if(!$target)fail('Account non disponibile.',404);
  C::exec('UPDATE users SET active=0,deleted_at=UTC_TIMESTAMP(),session_version=session_version+1 WHERE id=?',[$id]);
  C::exec("UPDATE notification_queue SET attempts=8,error='Account rimosso' WHERE recipient_email=(SELECT email FROM users WHERE id=?) AND kind='new_document' AND sent_at IS NULL",[$id]);C::audit((int)$u['id'],'user_removed',$id);C::go('/?tab=accounts&saved=1');
 }

 if($action==='save_settings'){$max=field('max_downloads',8);$days=field('retention_days',8);if(!preg_match('/^(0|[1-9][0-9]{0,5})$/D',$max)||!preg_match('/^(0|[1-9][0-9]{0,5})$/D',$days))fail('Inserisci numeri interi da 0 a 999999; zero indica nessun limite.');foreach(['max_downloads'=>(int)$max,'retention_days'=>(int)$days] as $key=>$value)C::exec('INSERT INTO portal_settings(setting_key,value_int) VALUES(?,?) ON DUPLICATE KEY UPDATE value_int=VALUES(value_int)',[$key,$value]);C::audit((int)$u['id'],'settings_updated');C::go('/?tab=settings&saved=1');}
 if($action==='create_operator'){$first=field('first_name',100);$last=field('last_name',100);$email=mb_strtolower(field('email',254));$password=(string)($_POST['password']??'');if($first===''||$last===''||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($password)<12||strlen($password)>200||strcasecmp($email,(string)C::config()['admin_email'])===0)fail('Controlla i dati dell’operatore e usa una password di almeno 12 caratteri.');C::exec("INSERT INTO users(first_name,last_name,email,password_hash,role) VALUES(?,?,?,?,'operator')",[$first,$last,$email,password_hash($password,PASSWORD_DEFAULT)]);C::audit((int)$u['id'],'operator_created',(int)C::db()->lastInsertId());C::go('/?tab=accounts&saved=1');}
 if($action==='toggle_operator'){$id=(int)($_POST['id']??0);$target=C::row("SELECT id,active FROM users WHERE id=? AND role='operator' AND deleted_at IS NULL",[$id]);if(!$target)fail('Operatore non trovato.',404);C::exec('UPDATE users SET active=?,session_version=session_version+1 WHERE id=?',[$target['active']?0:1,$id]);C::audit((int)$u['id'],$target['active']?'operator_disabled':'operator_enabled',$id);C::go('/?tab=accounts&saved=1');}
 if($action==='reset_operator_password'){$id=(int)($_POST['id']??0);$password=(string)($_POST['new_password']??'');if(strlen($password)<12||strlen($password)>200||!C::row("SELECT id FROM users WHERE id=? AND role='operator' AND deleted_at IS NULL",[$id]))fail('Operatore o password non validi.');C::exec('UPDATE users SET password_hash=?,session_version=session_version+1 WHERE id=?',[password_hash($password,PASSWORD_DEFAULT),$id]);C::audit((int)$u['id'],'operator_password_reset',$id);C::go('/?tab=accounts&saved=1');}
 if($action==='remove_operator'){$id=(int)($_POST['id']??0);if(!C::row("SELECT id FROM users WHERE id=? AND role='operator' AND deleted_at IS NULL",[$id]))fail('Operatore non trovato.',404);C::exec('UPDATE users SET active=0,deleted_at=UTC_TIMESTAMP(),session_version=session_version+1 WHERE id=?',[$id]);C::audit((int)$u['id'],'operator_removed',$id);C::go('/?tab=accounts&saved=1');}
 if($action==='company'){$n=field('name',180);if($n==='')fail('Inserisci il nome dell’azienda.');C::exec('INSERT INTO companies(name) VALUES(?)',[$n]);C::audit((int)$u['id'],'company_created',(int)C::db()->lastInsertId());C::go('/?tab=accounts&saved=1');}
 if($action==='plant'){$company=(int)($_POST['company_id']??0);$n=field('name',180);if(!$company||$n===''||!C::row('SELECT id FROM companies WHERE id=? AND active=1',[$company]))fail('Azienda o nome impianto non valido.');C::exec('INSERT INTO plants(company_id,name) VALUES(?,?)',[$company,$n]);C::audit((int)$u['id'],'plant_created',(int)C::db()->lastInsertId());C::go('/?tab=accounts&saved=1');}
 if($action==='account'){$company=(int)($_POST['company_id']??0);$plant=(int)($_POST['plant_id']??0);$first=field('first_name',100);$last=field('last_name',100);$email=mb_strtolower(field('email',254));$password=(string)($_POST['password']??'');if(!$first||!$last||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($password)<12||!C::row('SELECT id FROM plants WHERE id=? AND company_id=? AND active=1',[$plant,$company]))fail('Controlla i dati: password di almeno 12 caratteri e impianto appartenente all’azienda.');C::db()->beginTransaction();try{C::exec("INSERT INTO users(company_id,first_name,last_name,email,password_hash,role) VALUES(?,?,?,?,?,'client')",[$company,$first,$last,$email,password_hash($password,PASSWORD_DEFAULT)]);$id=(int)C::db()->lastInsertId();C::exec('INSERT INTO user_plants(user_id,plant_id) VALUES(?,?)',[$id,$plant]);C::audit((int)$u['id'],'user_created',$id);C::db()->commit();}catch(Throwable $e){C::db()->rollBack();throw $e;}C::go('/?tab=accounts&saved=1');}
 if($action==='edit_user'){$id=(int)($_POST['id']??0);$first=field('first_name',100);$last=field('last_name',100);$email=mb_strtolower(field('email',254));$target=C::row("SELECT id FROM users WHERE id=? AND role='client' AND deleted_at IS NULL",[$id]);if(!$target||$first===''||$last===''||!filter_var($email,FILTER_VALIDATE_EMAIL))fail('Dati account non validi.');C::exec('UPDATE users SET first_name=?,last_name=?,email=? WHERE id=?',[$first,$last,$email,$id]);C::audit((int)$u['id'],'user_updated',$id);C::go('/?tab=accounts&saved=1');}
 if($action==='grant_plant'||$action==='revoke_plant'){$id=(int)($_POST['id']??0);$plant=(int)($_POST['plant_id']??0);$target=C::row("SELECT id,company_id FROM users WHERE id=? AND role='client' AND deleted_at IS NULL",[$id]);if(!$target||!C::row('SELECT id FROM plants WHERE id=? AND company_id=? AND active=1',[$plant,$target['company_id']]))fail('Impianto non valido per questa persona.',403);if($action==='grant_plant')C::exec('INSERT IGNORE INTO user_plants(user_id,plant_id) VALUES(?,?)',[$id,$plant]);else C::exec('DELETE FROM user_plants WHERE user_id=? AND plant_id=?',[$id,$plant]);C::audit((int)$u['id'],$action,$id);C::go('/?tab=accounts&saved=1');}
 if($action==='reset_user_password'){$id=(int)($_POST['id']??0);$new=(string)($_POST['new_password']??'');if(strlen($new)<12||strlen($new)>200||!C::row("SELECT id FROM users WHERE id=? AND role='client' AND deleted_at IS NULL",[$id]))fail('Account o password non validi.');C::exec('UPDATE users SET password_hash=?,session_version=session_version+1 WHERE id=?',[password_hash($new,PASSWORD_DEFAULT),$id]);C::audit((int)$u['id'],'password_reset_by_admin',$id);C::go('/?tab=accounts&saved=1');}
 if($action==='toggle_user'){$id=(int)($_POST['id']??0);$target=C::row("SELECT id,role,active FROM users WHERE id=? AND role='client' AND deleted_at IS NULL",[$id]);if(!$target)fail('Account non valido.');C::exec('UPDATE users SET active=?,session_version=session_version+1 WHERE id=?',[$target['active']?0:1,$id]);C::audit((int)$u['id'],$target['active']?'user_disabled':'user_enabled',$id);C::go('/?tab=accounts&saved=1');}
 if($action==='upload'){
  $recipient=(int)($_POST['recipient_id']??0);$plant=(int)($_POST['plant_id']??0);
  $r=C::row("SELECT u.id,u.company_id,u.email,u.first_name,u.last_name FROM users u JOIN user_plants up ON up.user_id=u.id JOIN plants p ON p.id=up.plant_id AND p.company_id=u.company_id AND p.active=1 JOIN companies c ON c.id=u.company_id AND c.active=1 WHERE u.id=? AND p.id=? AND u.active=1 AND u.deleted_at IS NULL AND u.role='client'",[$recipient,$plant]);
  if(!$r)fail('Seleziona un destinatario e un impianto validi.');
  $folder=($_POST['upload_mode']??'')==='folder';$customTitle=!$folder&&($_POST['custom_title']??'')==='1';$title=$customTitle?field('title',220):'';if($customTitle&&$title==='')fail('Inserisci un titolo personalizzato oppure disattiva questa opzione.');$incoming=$_FILES[$folder?'files':'file']??null;
  if(!$incoming)fail('Seleziona un file o una cartella.');
  $files=[];if($folder){foreach((array)$incoming['name'] as $i=>$name)$files[]=['name'=>$name,'path'=>$incoming['full_path'][$i]??$name,'tmp'=>$incoming['tmp_name'][$i]??'','error'=>$incoming['error'][$i]??UPLOAD_ERR_NO_FILE,'size'=>$incoming['size'][$i]??0];}
  else $files[]=['name'=>$incoming['name'],'path'=>$incoming['name'],'tmp'=>$incoming['tmp_name'],'error'=>$incoming['error'],'size'=>$incoming['size']];
  if(!$files||count($files)>100||($folder&&count($files)!==(int)($_POST['expected_files']??0)))fail('Cartella non completa. Seleziona al massimo 100 file; verifica anche il limite file del server.');
  $cfg=C::config();$dir=$cfg['storage_path'];if(!is_dir($dir)||!is_writable($dir)||realpath($dir)===false||str_starts_with(realpath($dir),realpath(__DIR__)))fail('Archivio privato non configurato correttamente.',503);
  $allowed=['application/pdf','image/png','image/jpeg','text/plain','application/zip','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'];
  $size=0;$staged=[];
  foreach($files as $f){
   if($f['error']!==UPLOAD_ERR_OK||!is_uploaded_file($f['tmp'])||$f['size']<1||$f['size']>$cfg['max_upload_bytes'])fail('Un file supera il limite o non è stato caricato correttamente. Nessun file è stato consegnato.');
   $mime=(new finfo(FILEINFO_MIME_TYPE))->file($f['tmp']);if(!in_array($mime,$allowed,true))fail('La cartella contiene un tipo di file non consentito. Nessun file è stato consegnato.');
   $segments=explode('/',str_replace('\\','/',(string)$f['path']));if(in_array('..',$segments,true)||in_array('.',$segments,true))fail('Nome della cartella non valido.');
   $segments=array_values(array_filter(array_map('cleanFilename',$segments),fn($part)=>$part!==''));
   $name=cleanFilename((string)$f['name']);$label=$folder?mb_substr(implode(' / ',$segments)?:$name,0,220):($customTitle?$title:mb_substr($name,0,220));
   if($label==='')fail('Inserisci il titolo del documento.');
   $staged[]=['source'=>$f['tmp'],'name'=>$name,'title'=>$label,'mime'=>$mime,'bytes'=>(int)$f['size']];$size+=(int)$f['size'];
  }
  if($cfg['capacity_bytes']!==null){$used=(int)C::row('SELECT COALESCE(SUM(bytes),0) n FROM documents WHERE deleted_at IS NULL')['n'];if($used+$size>$cfg['capacity_bytes'])fail('Spazio insufficiente per i documenti selezionati.',507);}
  $moved=[];try{
   foreach($staged as &$file){$file['key']=bin2hex(random_bytes(32));$dest=rtrim($dir,'/').'/'.$file['key'];if(!move_uploaded_file($file['source'],$dest))throw new RuntimeException('Impossibile completare il caricamento.');chmod($dest,0600);$moved[]=$dest;$file['sha256']=hash_file('sha256',$dest);}unset($file);
   C::db()->beginTransaction();$ids=[];foreach($staged as $file){C::exec('INSERT INTO documents(company_id,plant_id,recipient_id,title,original_name,storage_key,mime,bytes,sha256,created_by) VALUES(?,?,?,?,?,?,?,?,?,?)',[$r['company_id'],$plant,$recipient,$file['title'],$file['name'],$file['key'],$file['mime'],$file['bytes'],$file['sha256'],$u['id']]);$id=(int)C::db()->lastInsertId();$ids[]=$id;C::audit((int)$u['id'],'document_uploaded',$id);}
   $summary=count($staged)===1?'Un documento ('.$staged[0]['title'].') è disponibile':'Sono disponibili '.count($staged).' nuovi documenti: '.implode(', ',array_column($staged,'title'));
   C::queue('new_document',$r['email'],count($staged)===1?'Nuovo documento disponibile · C.A. Automazione & Strumentazione':'Nuovi documenti disponibili · C.A. Automazione & Strumentazione','Buongiorno '.$r['first_name'].' '.$r['last_name'].', '.$summary.' nella tua Area Clienti: '.$cfg['base_url'],'new:'.hash('sha256',implode(':',$ids).':'.bin2hex(random_bytes(8))));C::db()->commit();
  }catch(Throwable $e){if(C::db()->inTransaction())C::db()->rollBack();foreach($moved as $path)if(is_file($path))unlink($path);throw $e;}
  C::go('/?saved=1');
 }
 if($action==='edit_document'){$id=(int)($_POST['id']??0);$title=field('title',220);if($title===''||!C::row('SELECT id FROM documents WHERE id=? AND deleted_at IS NULL',[$id]))fail('Documento non valido.');C::exec('UPDATE documents SET title=? WHERE id=?',[$title,$id]);C::audit((int)$u['id'],'document_updated',$id);C::go('/?saved=1');}
 if($action==='bulk_delete'){$ids=array_values(array_unique(array_filter(array_map('intval',(array)($_POST['ids']??[])),fn($n)=>$n>0)));if(!$ids||count($ids)>100)fail('Seleziona da 1 a 100 documenti.');$files=[];foreach($ids as $id){$d=C::row('SELECT id,storage_key FROM documents WHERE id=? AND deleted_at IS NULL',[$id]);if(!$d)fail('Uno dei documenti non è più disponibile.');$files[]=$d;}foreach($files as $f){$path=rtrim(C::config()['storage_path'],'/').'/'.$f['storage_key'];if(is_file($path)&&!is_writable($path))fail('Un file non può essere eliminato.');}C::db()->beginTransaction();try{foreach($files as $f){C::exec('UPDATE documents SET deleted_at=UTC_TIMESTAMP(),revoked_at=COALESCE(revoked_at,UTC_TIMESTAMP()) WHERE id=?',[$f['id']]);C::audit((int)$u['id'],'document_deleted',(int)$f['id']);}C::db()->commit();}catch(Throwable $e){C::db()->rollBack();throw $e;}foreach($files as $f){$path=rtrim(C::config()['storage_path'],'/').'/'.$f['storage_key'];if(is_file($path)&&!unlink($path))error_log('Cleanup file failed: '.$f['id']);}C::go('/?tab=archive&saved=1');}
 fail('Operazione sconosciuta.',404);
 }
 if($action==='reset'){$token=(string)($_GET['token']??'');$reset=preg_match('/^[a-f0-9]{64}$/D',$token)?C::row('SELECT t.id FROM password_reset_tokens t JOIN users u ON u.id=t.user_id AND u.active=1 AND u.deleted_at IS NULL WHERE t.token_hash=? AND t.used_at IS NULL AND t.expires_at>UTC_TIMESTAMP()',[hash('sha256',$token)]):false;if(!$reset)fail('Il collegamento è scaduto o già utilizzato.');page('Nuova password','<section class="login card"><h1>Nuova password</h1><form method="post" action="/?action=set_password">'.inputCsrf().'<input type="hidden" name="token" value="'.C::h($token).'"><label>Password (almeno 12 caratteri)<input type="password" name="new" minlength="12" autocomplete="new-password" required></label><button class="primary">Salva nuova password</button></form></section>');exit;}
 $u=C::user();if(!$u&&in_array($action,['view','download'],true))fail('Accesso richiesto.',401);if(!$u){$message=isset($_GET['reset_sent'])?'<div class="notice">Se l’indirizzo è associato a un account, riceverai un collegamento per reimpostare la password.</div>':(isset($_GET['password_updated'])?'<div class="notice">Password aggiornata. Ora puoi accedere.</div>':'');page('Accedi',$message.'<div class="login-layout"><section class="login card"><p class="eyebrow">Accesso riservato</p><h1>Area Clienti</h1><p>Consulta i documenti a te destinati con il tuo account personale.</p><form method="post" action="/?action=login">'.inputCsrf().'<label>Email<input type="email" name="email" autocomplete="username" required></label><label>Password<input type="password" name="password" autocomplete="current-password" required></label><fieldset class="privacy-fields"><legend>Informativa privacy</legend><p><a href="'.C::h((string)(C::config()['privacy_url']??'https://caautomazione.github.io/privacy/')).'" target="_blank" rel="noopener">Leggi l’informativa privacy</a> prima di accedere.</p><label class="check"><input type="checkbox" name="privacy_read" value="1"> Ho letto l’informativa privacy</label><label class="check"><input type="checkbox" name="remember_privacy" value="1"> Ricorda la presa visione per i prossimi accessi</label><small>Se la presa visione è già stata memorizzata, non devi selezionare di nuovo le caselle.</small></fieldset><div class="login-actions"><button class="primary">Accedi</button><button class="subtle reset-toggle" type="button" aria-expanded="false" aria-controls="reset-panel">Password dimenticata?</button></div></form><div class="reset-panel" id="reset-panel" hidden><h2>Reimposta la password</h2><p>Inserisci la tua email: riceverai un collegamento valido per 30 minuti.</p><form method="post" action="/?action=request_reset">'.inputCsrf().'<label>Email<input type="email" name="email" required></label><button class="subtle">Invia collegamento</button></form></div></section><aside class="login-aside"><img src="/assets/logo-rettangolare.svg" alt="C.A. Automazione &amp; Strumentazione"><h2>I tuoi documenti, in un unico spazio.</h2><p>Visualizza e scarica i file che ti sono stati assegnati. I documenti scaricati rimangono disponibili nell’archivio.</p></aside></div>');exit;}
 if($action==='view'||$action==='download'){if($action==='download'&&isset($_SESSION['impersonator_uid']))fail('In modalità amministrativa il download cliente non è disponibile.',403);$id=(int)($_GET['id']??0);$d=document($id,$u);if(!$d)fail('Documento non disponibile.',404);$path=rtrim(C::config()['storage_path'],'/').'/'.$d['storage_key'];if(!is_file($path))fail('File temporaneamente non disponibile.',503);$filename=cleanFilename($d['original_name']);if($action==='download'&&$u['role']==='client'){C::db()->beginTransaction();try{$locked=C::row('SELECT * FROM documents WHERE id=? FOR UPDATE',[$id]);if(!$locked||!C::available($locked)){C::db()->rollBack();fail('Il documento non è più disponibile per il download.',403);}C::exec('INSERT INTO download_events(document_id,user_id,ip) VALUES(?,?,?)',[$id,$u['id'],inet_pton($_SERVER['REMOTE_ADDR']??'')?:null]);$event=(int)C::db()->lastInsertId();C::exec('UPDATE documents SET first_download_at=COALESCE(first_download_at,UTC_TIMESTAMP()),download_count=download_count+1 WHERE id=?',[$id]);C::queue('download',C::config()['admin_email'],'Documento scaricato · C.A. Automazione & Strumentazione',$u['first_name'].' '.$u['last_name'].' ('.$u['email'].') ha avviato il download di '.$d['title'].' il '.C::date(gmdate('Y-m-d H:i:s')).' (ora italiana). Evento #'.$event,'download:'.$event);C::db()->commit();}catch(Throwable $e){C::db()->rollBack();throw $e;}}header('Content-Type: '.$d['mime']);header('Content-Length: '.filesize($path));header('X-Content-Type-Options: nosniff');header('Cache-Control: no-store, private');header('Content-Security-Policy: sandbox');header('Content-Disposition: '.($action==='download'?'attachment':'inline').'; filename="documento"; filename*=UTF-8\'\''.rawurlencode($filename));readfile($path);exit;}
 $saved=isset($_GET['saved'])?'<div class="notice">Modifica salvata.</div>':'';
 $tabs=['documents'=>'Gestione Documenti','accounts'=>'Gestione Accounts','archive'=>'Archivio file','settings'=>'Impostazioni'];if($u['role']==='operator')$tabs=['documents'=>'Gestione Documenti','archive'=>'Archivio file','settings'=>'Password'];$tab=(string)($_GET['tab']??'documents');if($u['role']==='client')$tabs=['documents'=>'Da scaricare','archive'=>'Archivio','settings'=>'Password'];if(!isset($tabs[$tab]))$tab='documents';
 $nav='<nav class="tabs">';foreach($tabs as $key=>$label)$nav.='<a class="'.($tab===$key?'active':'').'" href="/?tab='.$key.'">'.$label.'</a>';$nav.='</nav>';
 $body='<div class="heading"><div><p class="eyebrow">'.($u['role']==='admin'?'Amministrazione':($u['role']==='operator'?'Gestione documenti':'Documenti assegnati a te')).'</p><h1>Area Clienti</h1></div></div>'.$saved.$nav;
 if($tab==='documents'&&$u['role']!=='client'){
  $people=C::all("SELECT u.id,u.first_name,u.last_name,u.email,p.id plant_id,p.name plant,c.name company FROM users u JOIN companies c ON c.id=u.company_id JOIN user_plants up ON up.user_id=u.id JOIN plants p ON p.id=up.plant_id WHERE u.role='client' AND u.active=1 AND u.deleted_at IS NULL AND c.active=1 AND p.active=1 ORDER BY c.name,u.last_name");
  $opts='<option value="">Seleziona una persona</option>';foreach($people as $p)$opts.='<option value="'.$p['id'].':'.$p['plant_id'].'">'.C::h($p['first_name'].' '.$p['last_name'].' · '.$p['company'].' / '.$p['plant'].' · '.$p['email']).'</option>';
  $recipient='<label>Destinatario<select class="recipient-select" required>'.$opts.'</select></label><input type="hidden" name="recipient_id" class="recipient-id"><input type="hidden" name="plant_id" class="plant-id">';
  $body.='<div class="cols upload-options"><section class="card"><h2>Carica un documento</h2><p>Scegli la persona a cui consegnare il file.</p><form method="post" action="/?action=upload" enctype="multipart/form-data" data-upload-form>'.inputCsrf().$recipient.'<label>File<input type="file" name="file" required></label><label class="custom-title-toggle"><input type="checkbox" name="custom_title" value="1"> Usa un titolo diverso dal nome del file</label><div class="custom-title-field" hidden><label>Titolo personalizzato<input name="title" maxlength="220" disabled></label></div><button class="primary">Carica e avvisa il cliente</button></form></section>';
  $body.='<section class="card"><h2>Carica una cartella</h2><p>Tutti i file andranno alla stessa persona. Il percorso delle sottocartelle apparirà nel titolo. Massimo 100 file per invio.</p><form method="post" action="/?action=upload" enctype="multipart/form-data" data-upload-form>'.inputCsrf().'<input type="hidden" name="upload_mode" value="folder">'.$recipient.'<input type="hidden" name="expected_files" class="expected-files"><label>Cartella<input type="file" name="files[]" webkitdirectory directory multiple required></label><button class="primary">Carica la cartella e avvisa il cliente</button></form></section></div>';
  $docs=C::all('SELECT d.*,u.first_name,u.last_name,u.email,c.name company,p.name plant FROM documents d JOIN users u ON u.id=d.recipient_id JOIN companies c ON c.id=d.company_id JOIN plants p ON p.id=d.plant_id WHERE d.deleted_at IS NULL ORDER BY d.created_at DESC LIMIT 200');
 }
 elseif($u['role']==='client'&&($tab==='documents'||$tab==='archive')){$sql='SELECT d.*,p.name plant FROM documents d JOIN plants p ON p.id=d.plant_id JOIN companies c ON c.id=d.company_id WHERE d.recipient_id=? AND d.company_id=? AND d.deleted_at IS NULL AND d.revoked_at IS NULL AND c.active=1 AND p.active=1 AND EXISTS(SELECT 1 FROM user_plants up WHERE up.user_id=? AND up.plant_id=d.plant_id) AND d.first_download_at IS '.($tab==='archive'?'NOT NULL':'NULL').' ORDER BY d.created_at DESC';$docs=C::all($sql,[$u['id'],$u['company_id'],$u['id']]);}
 if(isset($docs)){
  $body.='<section class="card"><h2>'.($u['role']!=='client'?'Documenti consegnati':($tab==='archive'?'Archivio':'Da scaricare')).'</h2><div class="table-tools"><label>Cerca documenti<input type="search" class="table-search" placeholder="Cerca documento, destinatario o impianto" autocomplete="off"></label><span class="search-count" aria-live="polite"></span></div><div class="scroll"><table><thead><tr><th>Documento</th><th>'.($u['role']!=='client'?'Destinatario':'Impianto').'</th><th>Caricato</th><th>Azioni</th></tr></thead><tbody>';
  foreach($docs as $d){
   $body.='<tr><td><strong>'.C::h($d['title']).'</strong><small>'.C::h($d['original_name']).' · '.number_format($d['bytes']/1048576,1,',','.').' MB</small></td><td>'.($u['role']!=='client'?C::h($d['first_name'].' '.$d['last_name']).'<small>'.C::h($d['email'].' · '.$d['company'].' / '.$d['plant']).'</small>':C::h($d['plant'])).'</td><td>'.C::date($d['created_at']).'</td><td>';
   if($d['revoked_at'])$body.='<span class="pill">Non disponibile</span>';
   elseif($u['role']==='client'&&!C::available($d))$body.='<span class="pill">Accesso terminato</span>';
   else $body.='<div class="document-actions"><a class="action-button" href="/?action=view&id='.$d['id'].'" target="_blank" rel="noopener">Visualizza</a><a class="action-button" href="/?action=download&id='.$d['id'].'">Scarica</a>';
   if($u['role']!=='client')$body.='<details class="edit-title"><summary class="action-button">Modifica titolo</summary><form method="post" action="/?action=edit_document">'.inputCsrf().'<input type="hidden" name="id" value="'.$d['id'].'"><label>Nuovo titolo<input name="title" value="'.C::h($d['title']).'" required maxlength="220"></label><button class="subtle">Salva titolo</button></form></details>';
   if(!$d['revoked_at']&&($u['role']!=='client'||C::available($d)))$body.='</div>';
   if($u['role']!=='client')$body.='<small>Download: '.(int)$d['download_count'].'</small>';
   $body.='</td></tr>';
  }
  if(!$docs)$body.='<tr><td colspan="4">Nessun documento in questa sezione.</td></tr>';
  $body.='</tbody></table></div></section>';
 }
 if($tab==='accounts'&&$u['role']==='admin'){$companies=C::all('SELECT * FROM companies ORDER BY name');$plants=C::all('SELECT p.*,c.name company FROM plants p JOIN companies c ON c.id=p.company_id ORDER BY c.name,p.name');$users=C::all("SELECT u.*,c.name company FROM users u JOIN companies c ON c.id=u.company_id WHERE u.role='client' AND u.deleted_at IS NULL ORDER BY c.name,u.last_name");$co='';foreach($companies as $c)$co.='<option value="'.$c['id'].'">'.C::h($c['name']).'</option>';$po='';foreach($plants as $p)$po.='<option value="'.$p['id'].'" data-company="'.$p['company_id'].'">'.C::h($p['company'].' / '.$p['name']).'</option>';$body.='<div class="cols"><section class="card"><h2>Nuova azienda</h2><form method="post" action="/?action=company">'.inputCsrf().'<label>Nome<input name="name" required></label><button class="primary">Aggiungi azienda</button></form></section><section class="card"><h2>Nuovo impianto</h2><form method="post" action="/?action=plant">'.inputCsrf().'<label>Azienda<select name="company_id" required>'.$co.'</select></label><label>Nome impianto<input name="name" required></label><button class="primary">Aggiungi impianto</button></form></section></div><section class="card"><h2>Nuovo account cliente</h2><p>Consegna la password iniziale alla persona attraverso un canale sicuro. Il cliente potrà cambiarla dopo l’accesso.</p><form method="post" action="/?action=account">'.inputCsrf().'<div class="formgrid"><label>Nome<input name="first_name" required></label><label>Cognome<input name="last_name" required></label><label>Email<input name="email" type="email" required></label><label>Password iniziale<input name="password" type="password" minlength="12" required></label><label>Azienda<select name="company_id" id="company" required><option value="">Seleziona</option>'.$co.'</select></label><label>Impianto<select name="plant_id" id="plant" required><option value="">Seleziona</option>'.$po.'</select></label></div><button class="primary">Crea account</button></form><script>const company=document.getElementById("company"),plant=document.getElementById("plant");company.onchange=()=>{plant.value="";[...plant.options].forEach(o=>{if(o.value)o.hidden=o.dataset.company!==company.value})};company.onchange()</script></section>';}
 if($tab==='accounts'&&$u['role']==='admin'){
  $operators=C::all("SELECT id,first_name,last_name,email,active FROM users WHERE role='operator' AND deleted_at IS NULL ORDER BY last_name,first_name");
  $body.='<section class="card"><h2>Operatori CA Automazione</h2><p>Gli operatori possono caricare, consultare, rinominare ed eliminare documenti. Non possono creare o modificare account, aziende e impianti.</p><form method="post" action="/?action=create_operator">'.inputCsrf().'<div class="formgrid"><label>Nome<input name="first_name" maxlength="100" required></label><label>Cognome<input name="last_name" maxlength="100" required></label><label>Email<input type="email" name="email" maxlength="254" required></label><label>Password iniziale<input type="password" name="password" minlength="12" required></label></div><button class="primary">Crea operatore</button></form>';
  if($operators){$body.='<h3>Account operatori</h3><div class="operator-list">';foreach($operators as $op){$id=(int)$op['id'];$body.='<details class="account"><summary><strong>'.C::h($op['first_name'].' '.$op['last_name']).'</strong> · '.($op['active']?'Attivo':'Disattivato').'<small>'.C::h($op['email']).'</small></summary><div class="account-tools"><form method="post" action="/?action=toggle_operator">'.inputCsrf().'<input type="hidden" name="id" value="'.$id.'"><button class="subtle">'.($op['active']?'Disattiva':'Riattiva').'</button></form><form method="post" action="/?action=remove_operator" onsubmit="return confirm(\'Rimuovere questo operatore? Perderà subito accesso al portale.\')">'.inputCsrf().'<input type="hidden" name="id" value="'.$id.'"><button class="danger">Rimuovi operatore</button></form></div><form method="post" action="/?action=reset_operator_password">'.inputCsrf().'<input type="hidden" name="id" value="'.$id.'"><label>Nuova password (almeno 12 caratteri)<input type="password" name="new_password" minlength="12" required></label><button class="subtle">Reimposta password</button></form></details>';} $body.='</div>';} $body.='</section>';
 }
 if($tab==='accounts'&&$u['role']==='admin'){
  $grants=C::all('SELECT user_id,plant_id FROM user_plants');$allowed=[];foreach($grants as $g)$allowed[(int)$g['user_id']][(int)$g['plant_id']]=true;
  $access=C::all('SELECT a.user_id,a.ip,a.user_agent,a.occurred_at FROM access_events a ORDER BY a.occurred_at DESC LIMIT 500');$lastAccess=[];foreach($access as $event)if(!isset($lastAccess[(int)$event['user_id']]))$lastAccess[(int)$event['user_id']]=$event;
  $body.='<section class="card"><h2>Gestione account e permessi</h2><p>Apri una persona per aggiornare i dati e gli impianti consentiti.</p><div class="table-tools"><label>Cerca clienti<input type="search" class="account-search" placeholder="Cerca nome, email o azienda" autocomplete="off"></label><span class="search-count" aria-live="polite"></span></div><div class="account-list">';
  foreach($users as $person){
   $id=(int)$person['id'];$body.='<details class="account"><summary><strong>'.C::h($person['first_name'].' '.$person['last_name']).'</strong> · '.C::h($person['company']).' · '.($person['active']?'Attivo':'Disattivato').'<small>'.C::h($person['email']).'</small></summary>';
   $plantsLabel=[];foreach($plants as $plant)if(isset($allowed[$id][(int)$plant['id']]))$plantsLabel[]=$plant['name'];
   $accessRecord=$lastAccess[$id]??null;$ip=$accessRecord&&$accessRecord['ip']?inet_ntop($accessRecord['ip']):'Non disponibile';
   $body.='<div class="account-meta"><div><strong>Credenziali</strong><span>'.C::h($person['email']).' · Password protetta, non visualizzabile</span></div><div><strong>Azienda e impianti</strong><span>'.C::h($person['company'].' · '.(implode(', ',$plantsLabel)?:'Nessun impianto')).'</span></div><div><strong>Stato account</strong><span>'.($person['active']?'Attivo':'Disattivato').'</span></div><div><strong>Ultimo accesso</strong><span>'.($accessRecord?C::date($accessRecord['occurred_at']).' · IP '.C::h($ip):'Mai effettuato').'</span></div></div>';
   $body.='<form method="post" action="/?action=edit_user">'.inputCsrf().'<input type="hidden" name="id" value="'.$id.'"><div class="formgrid"><label>Nome<input name="first_name" value="'.C::h($person['first_name']).'" required></label><label>Cognome<input name="last_name" value="'.C::h($person['last_name']).'" required></label><label>Email<input name="email" type="email" value="'.C::h($person['email']).'" required></label></div><button class="subtle">Salva account</button></form>';
   $body.='<h3>Impianti consentiti</h3><div class="plant-list">';foreach($plants as $plant)if((int)$plant['company_id']===(int)$person['company_id']){$has=isset($allowed[$id][(int)$plant['id']]);$body.='<form method="post" action="/?action='.($has?'revoke_plant':'grant_plant').'">'.inputCsrf().'<input type="hidden" name="id" value="'.$id.'"><input type="hidden" name="plant_id" value="'.$plant['id'].'"><span>'.C::h($plant['name']).'</span><button class="subtle">'.($has?'Rimuovi accesso':'Concedi accesso').'</button></form>';}$body.='</div>';
   $body.='<div class="account-tools"><form method="post" action="/?action=toggle_user">'.inputCsrf().'<input type="hidden" name="id" value="'.$id.'"><button class="subtle">'.($person['active']?'Disattiva':'Riattiva').'</button></form><form method="post" action="/?action=impersonate">'.inputCsrf().'<input type="hidden" name="id" value="'.$id.'"><button class="subtle"'.($person['active']?'':' disabled').'>Entra come cliente</button></form><form method="post" action="/?action=remove_user" onsubmit="return confirm(\'Rimuovere questo account? Perderà subito accesso ai documenti.\')">'.inputCsrf().'<input type="hidden" name="id" value="'.$id.'"><button class="danger">Rimuovi account</button></form></div><form method="post" action="/?action=reset_user_password">'.inputCsrf().'<input type="hidden" name="id" value="'.$id.'"><label>Imposta una nuova password (non sarà mostrata in seguito)<input type="password" name="new_password" minlength="12" required></label><button class="subtle">Reimposta password</button></form></details>';
  }$body.='</div></section><section class="card"><h2>Accessi recenti</h2><p>Ora italiana e indirizzo IP visto dal server. L’indirizzo IP non indica con certezza la posizione fisica.</p><div class="table-tools"><label>Cerca in questa sezione<input type="search" class="table-search" placeholder="Cerca per nome, documento, azienda o impianto" autocomplete="off"></label><span class="search-count" aria-live="polite"></span></div><div class="scroll"><table><thead><tr><th>Persona</th><th>Data e ora</th><th>Indirizzo IP</th><th>Browser</th></tr></thead><tbody>';foreach(array_slice($access,0,100) as $event){$name=C::row('SELECT first_name,last_name FROM users WHERE id=?',[$event['user_id']]);$body.='<tr><td>'.C::h($name?($name['first_name'].' '.$name['last_name']):'Account rimosso').'</td><td>'.C::date($event['occurred_at']).'</td><td>'.C::h($event['ip']?inet_ntop($event['ip']):'Non disponibile').'</td><td><small>'.C::h(mb_substr($event['user_agent']??'',0,130)).'</small></td></tr>';}if(!$access)$body.='<tr><td colspan="4">Nessun accesso registrato.</td></tr>';$body.='</tbody></table></div></section>';
 }
 if($tab==='archive'&&$u['role']!=='client'){
  $files=C::all('SELECT d.id,d.title,d.bytes,d.created_at,d.deleted_at,d.download_count,(SELECT MAX(e.started_at) FROM download_events e WHERE e.document_id=d.id) last_download_at,u.first_name,u.last_name,c.name company FROM documents d JOIN users u ON u.id=d.recipient_id JOIN companies c ON c.id=d.company_id ORDER BY d.created_at DESC LIMIT 500');
  $used=(int)C::row('SELECT COALESCE(SUM(bytes),0) n FROM documents WHERE deleted_at IS NULL')['n'];
  $body.='<section class="card"><h2>Archivio file</h2><p>File attivi: '.number_format($used/1073741824,2,',','.').' GiB. La soglia email è 2 GiB residui, quando la quota è configurata.</p><form method="post" action="/?action=bulk_delete" onsubmit="return confirm(\'Eliminare i documenti selezionati? I clienti perderanno accesso e i file verranno rimossi.\')">'.inputCsrf().'<div class="table-tools"><label>Cerca nell’archivio<input type="search" class="table-search" placeholder="Cerca documento o destinatario" autocomplete="off"></label><span class="search-count" aria-live="polite"></span></div><div class="scroll"><table><thead><tr><th>Seleziona</th><th>Documento</th><th>Destinatario</th><th>Caricato</th><th>Ultimo download</th><th>N. download</th><th>Dimensione</th></tr></thead><tbody>';
  foreach($files as $f)$body.='<tr><td>'.($f['deleted_at']?'—':'<input type="checkbox" name="ids[]" value="'.$f['id'].'" aria-label="Seleziona '.C::h($f['title']).'">').'</td><td>'.C::h($f['title']).($f['deleted_at']?' <small>Eliminato</small>':'').'</td><td>'.C::h($f['first_name'].' '.$f['last_name'].' · '.$f['company']).'</td><td>'.C::date($f['created_at']).'</td><td>'.($f['last_download_at']?C::date($f['last_download_at']):'—').'</td><td>'.(int)$f['download_count'].'</td><td>'.number_format($f['bytes']/1048576,1,',','.').' MB</td></tr>';
  if(!$files)$body.='<tr><td colspan="7">Nessun file.</td></tr>';
  $body.='</tbody></table></div><button class="danger">Elimina selezionati</button></form></section>';
 }
 if($tab==='settings'&&$u['role']==='admin'){$policy=C::policy();$body.='<section class="card"><h2>Regole dei documenti</h2><p>Zero significa illimitato. I limiti si applicano subito anche ai file già caricati. Alla scadenza il file resta conservato per la gestione amministrativa, ma il cliente non può più aprirlo né scaricarlo.</p><form method="post" action="/?action=save_settings">'.inputCsrf().'<div class="formgrid"><label>Download massimi per documento<input type="number" name="max_downloads" min="0" max="999999" value="'.$policy['max_downloads'].'" required></label><label>Giorni di accesso dalla data di caricamento<input type="number" name="retention_days" min="0" max="999999" value="'.$policy['retention_days'].'" required></label></div><button class="primary">Salva regole</button></form><p>Dimensione massima per singolo file: '.number_format(C::config()['max_upload_bytes']/1048576,0,',','.').' MB. Email notifiche: '.C::h(C::config()['admin_email']).'. Questi dati tecnici si configurano sul server.</p></section>';}
 if($tab==='settings')$body.='<section class="card narrow"><h2>Cambia password</h2><form method="post" action="/?action=password">'.inputCsrf().'<label>Password attuale<input type="password" name="old" required></label><label>Nuova password (almeno 12 caratteri)<input type="password" name="new" minlength="12" required></label><button class="primary">Aggiorna password</button></form></section>';
 page('Area Clienti',$body,$u);
} catch(Throwable $e){error_log('Portal error: '.$e->getMessage());http_response_code(503);page('Servizio non disponibile','<section class="card"><h1>Servizio temporaneamente non disponibile</h1><p>Riprova più tardi o contatta C.A. Automazione &amp; Strumentazione.</p></section>');}
